### ISSUE TITLE
Step 2: 🧑‍🤝‍🧑 Conduct Kickoff meeting

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v37-geckos-team-08#5]
**__Task Description__**
- [ ] Using everyone's availability posted to When2Meet schedule a Kickoff meeting
- [ ] Use the [Kickoff meeting template](https://docs.google.com/document/d/1ozP5lLj_R0kqCWdXEpFDR6sIlP9miXp74DFKZlJyktE/edit?usp=sharing) in the shared document directory we've provided to guide the discussion and to record notes, decisions, and assignments
- [ ] Set a time for your next meeting for later in the week

**__Technical Considerations__**
N/a

**__Additional Considerations__**
N/a

**__Resources__**
[Conduct Kickoff Meeting (Chingu Handbook)](https://www.notion.so/Voyages-8d8e16a5f86e42a88d9ace16bc555f18#7bf53dc88d9146fd92673ec72d283b2b)

**Member of Epic:** #16
