### ISSUE TITLE
Step 4: 📤 Define & prioritize MVP features

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v37-geckos-team-08#7]
**__Task Description__**
- [ ] Each team member should add their ideas to the [Project Vision & Feature Planning template](https://docs.google.com/document/d/1pG-6ihL47P6IpMtcgVeb5_DWoatZcsMTwx_lGDmfh9o/edit?usp=sharing) before the team meeting
- [ ] Prioritize each feature - _Must Have_, _Should Have_, _Nice to Have_
- [ ] Meet with the team to review each feature & refine priorities

**__Technical Considerations__**
N/a

**__Additional Considerations__**
All _Must Have_ tasks will make up your MVP. Make sure that you control the scope of the project by limiting the number of _Must Have_ features to the ones you can reasonably complete by the end of Sprint 6.

Remember that you can always add new features once you complete the MVP.

**__Resources__**
[Choose a Project & create a Vision Statement (Chingu Handbook)](https://www.notion.so/Voyages-8d8e16a5f86e42a88d9ace16bc555f18#f98c81e380cd47819e6a5072e017d17b)
[Define & Prioritize MVP features (Chingu Handbook)](https://www.notion.so/Voyages-8d8e16a5f86e42a88d9ace16bc555f18#81bd923bd4b64f91ab33faf77384b4bd)

**Member of Epic:** #16
